apiVersion: apps/v1
kind: Deployment
metadata:
  name: issue-tracker-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: issue-tracker
  template:
    metadata:
      labels:
        app: issue-tracker
    spec:
      containers:
      - name: php-app
        image: sanmargparanjpe/issue-tracker:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: issue-tracker-service
spec:
  type: NodePort
  selector:
    app: issue-tracker
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
